// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvaRqgDJcnDgNpictlQYlVAxq5z8xoNC8',
    appId: '1:677302366548:web:74d13a7aadb435932998c1',
    messagingSenderId: '677302366548',
    projectId: 'testfirebasedb-19176',
    authDomain: 'testfirebasedb-19176.firebaseapp.com',
    storageBucket: 'testfirebasedb-19176.appspot.com',
    measurementId: 'G-G9J52FX642',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPTlmejCWG1ZWFZxUqTLpKWl73clKAkf0',
    appId: '1:677302366548:android:8e8c01a9edb43b552998c1',
    messagingSenderId: '677302366548',
    projectId: 'testfirebasedb-19176',
    storageBucket: 'testfirebasedb-19176.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoqqfo_5kieJANqHHo7JDr8b6jEyBlqHY',
    appId: '1:677302366548:ios:5696693659f6beef2998c1',
    messagingSenderId: '677302366548',
    projectId: 'testfirebasedb-19176',
    storageBucket: 'testfirebasedb-19176.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoqqfo_5kieJANqHHo7JDr8b6jEyBlqHY',
    appId: '1:677302366548:ios:cfd4fc696c3a2e6b2998c1',
    messagingSenderId: '677302366548',
    projectId: 'testfirebasedb-19176',
    storageBucket: 'testfirebasedb-19176.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
